### ISSUE TITLE
support for 24h clocks/ localization problem

### ISSUE THREAD

**Issue by rk-exxec** [MadSquids/SimpleClock#1] opened 2024-12-06 22:57 UTC
Hey,
i love this mod for tracking my playtime.
My computers locale is de-DE.

The time shows as "07:53 nachmittag" for 07:53 pm, at least i assume it says that, since the text is cut off because the text box is not large enough.

Can you check whats going on there?

Thanks so much

**Comment by rk-exxec** [comment] 2024-12-06 23:05
https://github.com/MadSquids/SimpleClock/blob/424237f62107f704078dc1033e92ca39faa5aca9/SimpleClock/SimpleClockController.cs#L108

I think you can replace the `"hh:mm tt"` format string with just `"t"` to make it locale-agnostic.

https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#ShortTime

**Comment by MadSquids** [comment] 2024-12-07 00:18
I'm glad to hear you are enjoying this. I will look into this, Thanks for the report!

**Comment by MadSquids** [comment] 2024-12-07 09:08
Alright, so the issue is fixed in version 1.0.1, which I will release momentarily. Thanks for suggesting using "t" which fixed it. Feel free to let me know of any other issues or things you'd like to see from this plugin.

Enjoy,
MadSquids

**Closed as completed by MadSquids** 2024-12-07 09:08 UTC
Labels: bug
